FROM golang:1.19 AS builder
WORKDIR /workspace
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main cmd/api/main.go

FROM gcr.io/distroless/static:latest
COPY --from=builder /workspace/main /app/main
USER nonroot
CMD ["/app/main"]