FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y curl \
  && curl -L -o /usr/local/bin/atlas https://release.ariga.io/atlas/atlas-linux-arm64-latest \
  && chmod +x /usr/local/bin/atlas \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
ENTRYPOINT [ "atlas" ]