import { Serve } from "bun";
import { createYoga } from "graphql-yoga";
import { getSchema } from "../schema"; // Will be generated by Grats

const yoga = createYoga<Serve>({ schema: getSchema() });
// @ts-ignore
const server = Bun.serve(yoga);

console.info(
	`Running a GraphQL API server at http://${server.hostname}:${server.port}/graphql`,
);
