type Post {
  id: ID!
  title: String!
  body: String!
  createdAt: Time!
  updatedAt: Time!

  tags: [Tag!]!
}

type Query {
  posts: [Post!]!
}

input CreatePostParams {
  title: String!
  body: String!
}

extend type Mutation {
  createPost(input: CreatePostParams): Post!
  connectTag(postId: ID!, tagId: ID!): MessageResponse!
}
