type Post {
  id: UUID!
  title: String!
  body: String!
  createdAt: Time!
  updatedAt: Time!

  tags: [Tag!]!
}

extend type Query {
  posts: [Post!]!
}

input CreatePostParams {
  title: String!
  body: String!
}

extend type Mutation {
  createPost(input: CreatePostParams): Post!
  connectTag(postId: UUID!, tagId: UUID!): MessageResponse!
}
