type User {
  id: UUID!
  name: String!
  email: String!

  posts: [Post!]!
  postCount: Int!
}

input CreateUserParams {
  name: String!
  email: String!
}

input UpdateUserParams {
  name: String
  email: String
}

type Query {
  user(id: UUID!): User
  users: [User!]!
}

type Mutation {
  createUser(input: CreateUserParams): User!
  updateUser(input: UpdateUserParams): User!
}
