type User {
  id: ID!
  name: String!
  email: String!
  posts: [Post!]!
}

type Query {
  users: [User!]!
  user(id: ID!): User
}

input CreateUserInput {
  name: String!
  email: String!
}

type Mutation {
  createUser(input: CreateUserInput!): User!
}
