services:
  crdb:
    image: cockroachdb/cockroach:v22.1.0
    ports:
      - "26257:26257"
      - "9090:8080"
    command: start-single-node --insecure
    volumes:
      - "${PWD}/.data/crdb:/cockroach/cockroach-data"
