// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"go-gqlgen-ent/ent"
)

type Article struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	CreatedAt string    `json:"createdAt"`
	UpdatedAt string    `json:"updatedAt"`
	User      *ent.User `json:"user"`
}
