type Article {
  slug: String!
  title: String!
  description: String!
  body: String!
}

type Tag {
  id: ID!
  name: String!
}

extend type Query {
  article(slug: String!): Article
  articles: [Article!]!
}

extend type Article {
  tagList: [Tag!]!
  author: User!
}
