// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"

	"go-gqlgen-sqlc/graphql/scalar"
)

type Post struct {
	ID        scalar.UUID
	Title     string
	Body      string
	UserID    scalar.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type PostsTag struct {
	PostID scalar.UUID
	TagID  scalar.UUID
}

type Tag struct {
	ID   scalar.UUID
	Text string
}

type User struct {
	ID        scalar.UUID
	Name      string
	Email     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
