// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
)

type Post struct {
	ID        int64
	Title     string
	Body      string
	UserID    int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type PostsTag struct {
	PostID int64
	TagID  int64
}

type Tag struct {
	ID   int64
	Text string
}

type User struct {
	ID        int64
	Name      string
	Email     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
