// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: user.sql

package db

import (
	"context"

	"github.com/lib/pq"
	"go-gqlgen-sqlc/graphql/scalar"
)

const createUser = `-- name: CreateUser :one
insert into users (id, name, email, password_hash) values($1, $2, $3, $4) returning id, name, email, created_at, updated_at, password_hash
`

type CreateUserParams struct {
	ID           scalar.UUID
	Name         string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return &i, err
}

const getPostCountsByUserIds = `-- name: GetPostCountsByUserIds :many
select user_id, count(*) from posts where user_id = ANY($1::uuid[])
`

type GetPostCountsByUserIdsRow struct {
	UserID scalar.UUID
	Count  int64
}

func (q *Queries) GetPostCountsByUserIds(ctx context.Context, userIds []scalar.UUID) ([]*GetPostCountsByUserIdsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostCountsByUserIds, pq.Array(userIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetPostCountsByUserIdsRow
	for rows.Next() {
		var i GetPostCountsByUserIdsRow
		if err := rows.Scan(&i.UserID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
select id, name, email, created_at, updated_at, password_hash from users where id = $1
`

func (q *Queries) GetUser(ctx context.Context, id scalar.UUID) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return &i, err
}

const getUsers = `-- name: GetUsers :many
select id, name, email, created_at, updated_at, password_hash from users
`

func (q *Queries) GetUsers(ctx context.Context) ([]*User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
update users set 
  name = $1,
  email = $2 
where id = $3 returning id, name, email, created_at, updated_at, password_hash
`

type UpdateUserParams struct {
	Name  string
	Email string
	ID    scalar.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg *UpdateUserParams) (*User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.Name, arg.Email, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return &i, err
}
