// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"go-gqlgen-bun-wire/app/infra/dao"
	"go-gqlgen-bun-wire/app/infra/db"
	"go-gqlgen-bun-wire/app/infra/loader"
	"go-gqlgen-bun-wire/app/resolver"
	"go-gqlgen-bun-wire/app/service"
)

// Injectors from wire.go:

func InitializeApp() *app {
	bunDB := db.NewDB()
	articleRepository := dao.NewArticle(bunDB)
	articleService := service.NewArticle(articleRepository)
	resolverResolver := resolver.NewResolver(articleService)
	loaders := loader.NewLoaders(bunDB)
	diApp := newApp(resolverResolver, loaders, bunDB)
	return diApp
}
