// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type ArticleConnection struct {
	// https://facebook.github.io/relay/graphql/connections.htm#sec-Edge-Types
	Edges []*ArticleEdge `json:"edges"`
	// https://facebook.github.io/relay/graphql/connections.htm#sec-undefined.PageInfo
	PageInfo *PageInfo `json:"pageInfo"`
}

type ArticleEdge struct {
	// https://facebook.github.io/relay/graphql/connections.htm#sec-Cursor
	Cursor string `json:"cursor"`
	// https://facebook.github.io/relay/graphql/connections.htm#sec-Node
	Node *Article `json:"node"`
}

type CreateMessageInput struct {
	Text     string `json:"text"`
	ToUserID string `json:"toUserId"`
}

type MaybeError struct {
	// Error message
	Error *string `json:"error"`
}

// PageInfo cursor, as defined in https://facebook.github.io/relay/graphql/connections.htm#sec-undefined.PageInfo
type PageInfo struct {
	// The cursor corresponding to the last nodes in edges. Null if the connection is empty.
	EndCursor *string `json:"endCursor"`
	// Used to indicate whether more edges exist following the set defined by the clients arguments.
	HasNextPage bool `json:"hasNextPage"`
	// Used to indicate whether more edges exist prior to the set defined by the clients arguments.
	HasPreviousPage bool `json:"hasPreviousPage"`
	// The cursor corresponding to the first nodes in edges. Null if the connection is empty.
	StartCursor *string `json:"startCursor"`
}
