type Article {
  id: ID!
  title: String!
  body: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  author: User!
}

type ArticleConnection {
  totalCount: Int!
  pageInfo: PageInfo!
  edges: [ArticleEdge!]!
}

type ArticleEdge {
  node: Article!
  cursor: Cursor
}

extend type Query {
  article(id: ID!): Article
  articles(
    after: Cursor
    first: Int
    before: Cursor
    last: Int
  ): ArticleConnection!
}
