type User {
  id: ID!
  name: String!
  email: String!
  articles(
    after: Cursor
    first: Int
    before: Cursor
    last: Int
  ): ArticleConnection!
  """
  ユーザーがいいねした記事一覧
  """
  likedArticles(
    after: Cursor
    first: Int
    before: Cursor
    last: Int
  ): ArticleConnection!
}

type UserConnection {
  totalCount: Int!
  pageInfo: PageInfo!
  edges: [UserEdge!]!
}

type UserEdge {
  node: User!
  cursor: Cursor
}

extend type Query {
  user(id: ID!): User
  users(after: Cursor, first: Int, before: Cursor, last: Int): UserConnection!
}

extend type Mutation {
  likeArticle(articleID: ID!): Response!
}
