// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"go-gqlgen-bun-wire/app"
	"go-gqlgen-bun-wire/app/infra/dao"
	"go-gqlgen-bun-wire/app/infra/db"
	"go-gqlgen-bun-wire/app/resolver"
	"go-gqlgen-bun-wire/app/service"
)

// Injectors from wire.go:

func InitializeApp() *app.App {
	bunDB := db.NewDB()
	articleRepository := dao.NewArticle(bunDB)
	articleService := service.NewArticle(articleRepository)
	resolverResolver := resolver.NewResolver(articleService)
	appApp := app.NewApp(resolverResolver, bunDB)
	return appApp
}
