name: next-urql-yoga-stack
on:
  push:
    paths:
      - next-urql-yoga-stack/**
      - .github/workflows/next-urql-yoga-stack.yml
    branches:
      - main
  pull_request:
    paths:
      - next-urql-yoga-stack/**
      - .github/workflows/next-urql-yoga-stack.yml
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: next-urql-yoga-stack
    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable pnpm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: next-urql-yoga-stack/pnpm-lock.yaml
      - run: pnpm i
      - run: pnpm run codegen
      - name: Validate that there is no diff in a codegen result for web
        run: git diff --exit-code --quiet
      - run: pnpm run build
      - run: pnpm run test
