name: nexus-realworld
on:
  push:
    paths:
      - nexus-realworld/**
      - .github/workflows/nexus-realworld.yml
    branches:
      - main
  pull_request:
    paths:
      - nexus-realworld/**
      - .github/workflows/nexus-realworld.yml
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nexus-realworld
    strategy:
      matrix:
        node-version:
          - 16.x
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: nexus-realworld/yarn.lock
      - run: yarn install
      - run: yarn workspace server run typegen
      - run: yarn workspace server run lint
      - run: yarn workspace server exec tsc --noEmit
      - run: yarn workspace server run build
      - name: codegen and typecheck for nextjs-apollo
        run: |
          yarn workspace nextjs-apollo run codegen
          yarn workspace nextjs-apollo exec tsc --noEmit
          yarn workspace nextjs-apollo run lint
      - name: codegen and typecheck for svelte-kit-apollo
        run: |
          yarn workspace svelte-kit-apollo run codegen
          yarn workspace svelte-kit-apollo run build
          yarn workspace svelte-kit-apollo exec tsc --noEmit
          yarn workspace svelte-kit-apollo run lint
          yarn workspace svelte-kit-apollo run check
