name: nexus-realworld
on:
  push:
    paths:
      - nexus-realworld/**
      - .github/**
    branches:
      - main
  pull_request:
    paths:
      - nexus-realworld/**
      - .github/**
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nexus-realworld
    strategy:
      matrix:
        node-version:
          - 16.x
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable pnpm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: nexus-realworld/pnpm-lock.yaml
      - run: pnpm i
      - run: pnpm --dir apps/server run typegen
      - run: pnpm --dir apps/server run lint
      - run: pnpm --dir apps/server exec tsc --noEmit
      - run: pnpm --dir apps/server run build
