name: nexus-realworld
on:
  push:
    paths:
      - nexus-realworld/**
      - .github/**
    branches:
      - main
  pull_request:
    paths:
      - nexus-realworld/**
      - .github/**
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nexus-realworld
    strategy:
      matrix:
        node-version:
          - 16.x
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable pnpm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: nexus-realworld/pnpm-lock.yaml
      - run: pnpm i
      - run: pnpm --dir apps/server run typegen
      - run: pnpm --dir apps/server run lint
      - run: pnpm --dir apps/server exec tsc --noEmit
      - run: pnpm --dir apps/server run build
      - name: codegen and typecheck for nextjs-apollo
        run: |
          pnpm --dir apps/server run dev &
          sleep 5
          pnpm --dir apps/nextjs-apollo run codegen
          pnpm --dir apps/nextjs-apollo exec tsc --noEmit
          pnpm --dir apps/nextjs-apollo run lint
      - name: codegen and typecheck for svelte-kit-apollo
        run: |
          pnpm --dir apps/server run dev &
          sleep 5
          pnpm --dir apps/svelte-kit-apollo run codegen
          pnpm --dir apps/svelte-kit-apollo exec tsc --noEmit
          pnpm --dir apps/svelte-kit-apollo run lint
          pnpm --dir apps/svelte-kit-apollo run check
