name: nexus-prisma
on:
  push:
    paths:
      - backend/nexus-prisma/**
      - .github/**
    branches:
      - main
  pull_request:
    paths:
      - backend/nexus-prisma/**
      - .github/**
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/nexus-prisma
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 17.x
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable pnpm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: backend/nexus-prisma/pnpm-lock.yaml
      - run: pnpm i
      - run: pnpm lint
      - run: pnpm tsc --noEmit
      - run: pnpm run build
      # - run: npm test
