name: type-graphql-realworld
on:
  push:
    paths:
      - type-graphql-realworld/**
      - .github/workflows/type-graphql-realworld.yml
    branches:
      - main
  pull_request:
    paths:
      - type-graphql-realworld/**
      - .github/workflows/type-graphql-realworld.yml
    branches:
      - main
defaults:
  run:
    working-directory: type-graphql-realworld
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable pnpm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm i
      - name: codegen and typecheck
        run: |
          cp apps/apollo-typegraphql-prisma/src/env.sample.ts apps/apollo-typegraphql-prisma/src/env.ts
          pnpm --dir apps/apollo-typegraphql-prisma dev &
          sleep 5
          pnpm --dir apps/react-location-apollo codegen
          pnpm --dir apps/svelte-urql codegen